name: maybe
version: 0.1.0
homepage: https://github.com/morloclib/maybe
synopsis: Combinators for optional values
description: Functions for querying, transforming, and composing optional (nullable) values.
category: data
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/maybe
bug-reports: https://github.com/morloclib/maybe
